# Dream config
attention_layers: 2
hidden_size: 64
model_hidden: 64
embed_size: 64
n_categoricals: 8
n_classes: 8
deterministic_size: 64
stochastic_size: n_classes*n_categoricals
feat_size: stochastic+deterministic
global_feat: feat+embed_size

reward_layers: 2
reward_hidden: 64
value_layers: 2
value_hidden: 64
pcont_layers: 2
pcont_hidden: 64
action_layers: 2
action_hidden: 64

activation_func: relu
action_type: discrete
